<a href="https://colab.research.google.com/github/shahmonil/Machine-Learning/blob/master/ANN_with_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1]
y = dataset.iloc[:,-1]

In [31]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [0]:
X['Gender'] = X.Gender.map({'Male':1, 'Female':0})

In [0]:
dummy1 = pd.get_dummies(X['Geography'])

In [0]:
X = pd.concat([X,dummy1], axis=1)

In [0]:
X.drop(columns='Geography', inplace=True)

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc  = StandardScaler()

In [39]:
X_test

CreditScore  Gender  Age  Tenure  ...  EstimatedSalary  France  Germany  Spain
9394          597       0   35       8  ...        192852.67       0        1      0
898           523       0   40       2  ...        128702.10       1        0      0
2398          706       0   42       8  ...         75732.25       0        0      1
5906          788       1   32       4  ...         89368.59       1        0      0
2343          706       1   38       5  ...        135662.17       0        1      0
...           ...     ...  ...     ...  ...              ...     ...      ...    ...
1037          625       0   24       1  ...        180969.55       1        0      0
2899          586       0   35       7  ...         70760.69       1        0      0
9549          578       1   36       1  ...        141533.19       0        0      1
2740          650       1   34       4  ...         11276.48       0        1      0
6690          573       1   30       8  ...        192950.60       0        1      0

[2000 rows x 12 columns]

In [0]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
#Starting with ANN

In [0]:
ann  = tf.keras.Sequential()

In [0]:
#adding first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  #rectifier ativation function

In [0]:
#adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
#adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))     #unit 1 because binary output

In [0]:
#compiling ann
ann.compile(optimizer= 'adam',loss= 'binary_crossentropy',metrics=['accuracy'])
#categorical_crossentropy for multiclass

In [46]:
ann.fit(X_train, y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6084 - accuracy: 0.7089
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4597 - accuracy: 0.8095
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4335 - accuracy: 0.8161
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.8180
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4191 - accuracy: 0.8220
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8234
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4071 - accuracy: 0.8263
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3984 - accuracy: 0.8324
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3876 - accuracy: 0.8386
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3770 - accura

In [47]:
ann.predict(sc.transform([[600,1,40, 3,60000,2,1,1,50000,1,0,0]]))

array([[0.02737096]], dtype=float32)

In [0]:
y_pred = ann.predict(X_test)
y_pred2 = np.where(y_pred > 0.5,1,0)


In [50]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [51]:
y_pred

array([[0.2131407 ],
       [0.33848163],
       [0.11415175],
       ...,
       [0.17511633],
       [0.1308536 ],
       [0.26663196]], dtype=float32)

In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test, y_pred2)

[[1507   88]
 [ 197  208]]


0.8575